const articles = require("./articles")
const getTagsclass = require("./getTagsclass")
const getCount = require("./getCount")
const comments = require("./comments")
const getTime = require("./getTime")
const msgBoard = require("./msgBoard")
const vistors = require("./vistors")
const login = require("./login")
const copyData = require("./copyData")
const news = require("./news")
const reviseKey = require("./reviseKey")
const donload = require("./donload")

module.exports = (app) => {
	app.use(articles)
	app.use(getTagsclass)
	app.use(getCount)
	app.use(comments)
	app.use(getTime)
	app.use(msgBoard)
	app.use(login)
	app.use(vistors)
	app.use(copyData)
	app.use(news)
	app.use(reviseKey)
	app.use(donload)
}
